name: Compile IPK

on:
  push:
    paths:
      - 'luci-app-whatsapp-bot/Makefile'
  workflow_dispatch:

jobs:
  build:
    name: Compile IPK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      run: |
        sudo -E apt-get update > /dev/null 2>&1
        sudo -E apt-get install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget > /dev/null 2>&1
        sudo -E apt-get autoremove --purge > /dev/null 2>&1
        sudo -E apt-get clean > /dev/null 2>&1
        wget https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz  > /dev/null 2>&1
        tar xJf openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz  > /dev/null 2>&1
        mv openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64 sdk  > /dev/null 2>&1

    - name: Setup feeds
      run: |
        cd sdk
        ./scripts/feeds update -a  > /dev/null 2>&1
        ./scripts/feeds install -a  > /dev/null 2>&1

    - name: Get Version
      id: get_version
      run: |
        cd luci-app-whatsapp-bot
        echo "whatsapp_bot=$(grep 'PKG_VERSION:=' Makefile | awk -F '=' '{print $2}' | tr -d ' ')" >> $GITHUB_OUTPUT

    - name: Prepare Package
      run: |
        cd sdk
        mkdir -p package/luci-app-whatsapp-bot
        cp -R ../luci-app-whatsapp-bot/* package/luci-app-whatsapp-bot/

    - name: Compile IPK
      run: |
        cd sdk && make defconfig
        sed -i 's/CONFIG_LUCI_SRCDIET=y/# CONFIG_LUCI_SRCDIET is not set/' .config
        sed -i 's/CONFIG_LUCI_JSMIN=y/# CONFIG_LUCI_JSMIN is not set/' .config
        sed -i 's/CONFIG_LUCI_CSSTIDY=y/# CONFIG_LUCI_CSSTIDY is not set/' .config
        sed -i 's/# CONFIG_NO_STRIP is not set/CONFIG_NO_STRIP=y/' .config
        sed -i 's/CONFIG_USE_STRIP=y/# CONFIG_USE_STRIP is not set/' .config
        sed -i 's/CONFIG_USE_SSTRIP=y/# CONFIG_USE_SSTRIP is not set/' .config
        (make package/luci-app-whatsapp-bot/compile V=s -j$(nproc) || echo "BUILD_FAILED=true" >> $GITHUB_ENV) > /dev/null 2>&1
        
    - name: Check Compile Failed
      if: env.BUILD_FAILED != 'true'
      run: |
        mv bin/packages/x86_64/base/luci-app-whatsapp-bot*.ipk ../luci-app-whatsapp-bot_${{ steps.get_version.outputs.whatsapp_bot }}_all.ipk
    
    - name: Create Release
      if: env.BUILD_FAILED != 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        release_date=$(date +'%Y.%m.%d')
        release_name="${{ steps.get_version.outputs.whatsapp_bot }}"
        release_tag="${release_date}"

        gh release create "$release_tag" \
          --title "$release_tag" \
          --generate-notes=false

    - name: Upload IPK
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        gh release upload ${{ steps.get_version.outputs.whatsapp_bot }} \
          ./luci-app-whatsapp-bot_${{ steps.get_version.outputs.whatsapp_bot }}_all.ipk
